### ISSUE TITLE
Multi Gpu training issue

### ISSUE THREAD

**Issue by NO2-yh** [VisionLearningGroup/DA_Detection#13]
Hi,
when i add `--mGPUs` for multi-gpu training , some errors occured to me as the following error informations.
DOES it support multi-gpu training???

Traceback (most recent call last):
131   File "trainval_net_global_local.py", line 201, in <module>
132     rois_label, out_d_pixel, out_d = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
133   File "/mnt/lustre/yanghang1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
134     result = self.forward(*input, **kwargs)
135   File "/mnt/lustre/yanghang1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 115, in forward
136     return self.gather(outputs, self.output_device)
137   File "/mnt/lustre/yanghang1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 127, in gather
138     return gather(outputs, output_device, dim=self.dim)
139   File "/mnt/lustre/yanghang1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
140     return gather_map(outputs)
141   File "/mnt/lustre/yanghang1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
142     return type(out)(map(gather_map, zip(*outputs)))
143   File "/mnt/lustre/yanghang1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
144     return Gather.apply(target_device, dim, *outputs)
145   File "/mnt/lustre/yanghang1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
146     ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
147   File "/mnt/lustre/yanghang1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in <lambda>
148     ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
149 RuntimeError: dimension specified as 0 but tensor has no dimensions

**Comment by NO2-yh** [comment]
By the way, sing gpu by remove `--mGPUs` worked nice

**Comment by lerndeep** [comment]
could you explain which line you change for multi-GPU training?
