### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.model.roi_crop._ext.roi_crop._roi_crop'

### ISSUE THREAD

**Issue by Daipuwei** [VisionLearningGroup/DA_Detection#24]
Traceback (most recent call last):
  File "trainval_net_global_local.py", line 25, in <module>
    from lib.model.utils.net_utils import weights_normal_init, save_net, load_net, \
  File "E:\DA_Detection-master\lib\model\utils\net_utils.py", line 10, in <module>
    from lib.model.roi_crop.functions.roi_crop import RoICropFunction
  File "E:\DA_Detection-master\lib\model\roi_crop\functions\roi_crop.py", line 4, in <module>
    from lib.model.roi_crop._ext import roi_crop
  File "E:\DA_Detection-master\lib\model\roi_crop\_ext\roi_crop\__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'lib.model.roi_crop._ext.roi_crop._roi_crop'

**Comment by JiahuaDong** [comment]
@Daipuwei   Hi, have you solved this problem? I have met the same issue.

**Comment by Daipuwei** [comment]
> @Daipuwei Hi, have you solved this problem? I have met the same issue.

Sorry, it's a difficult bug that I have not solved

**Comment by Daipuwei** [comment]
> @Daipuwei Hi, have you solved this problem? I have met the same issue.

could we talk about this bug via wechat? my wechat id is : dpw19960712

**Comment by ygzhu** [comment]
you can run `sh make.sh` [https://github.com/jwyang/faster-rcnn.pytorch/issues/324#issue-365083085](url)
if some errors happen, you can check whetherthe pytorch version matchs the cuda version

**Comment by ygzhu** [comment]
run `sh make.sh` jwyang/faster-rcnn.pytorch#324
if some errors happen, you can check whetherthe pytorch version matchs the cuda version
