### ISSUE TITLE
import error when train

### ISSUE THREAD

**Issue by snslmi** [VisionLearningGroup/DA_Detection#36]
i have import error when try to train 
could you be so kind to help me?
thank you In advance

:~/DA_Detection$ CUDA_VISIBLE_DEVICES=$1 python trainval_net_global_local.py --cuda --net res101 --dataset pascal_voc_water --dataset_t water --gc --lc --save_dir $2
Traceback (most recent call last):
  File "trainval_net_global_local.py", line 25, in <module>
    from model.utils.net_utils import weights_normal_init, save_net, load_net, \
  File "/home/DA_Detection/lib/model/utils/net_utils.py", line 10, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/DA_Detection/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/DA_Detection/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /home/DA_Detection/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaPopCallConfiguration

**Comment by youzi260** [comment]
I had the same problem as you. Did you solve it？
