### ISSUE TITLE
RuntimeError: size mismatch occurs when using `--lc --gc` for `trainval_net_global_local.py` 

### ISSUE THREAD

**Issue by kinredon** [VisionLearningGroup/DA_Detection#4]
I want to use local context and global context with argument `--lc --gc` for `trainval_net_global_local.py` .

Command as followed:
`CUDA_VISIBLE_DEVICES=4 python trainval_net_global_local.py --dataset pascal_voc_0712 --dataset_t clipart --net res101 --cuda --bs 2 --lc --gc`

And I got a `RuntimeError: size mismatch` error.

```
Traceback (most recent call last):
  File "trainval_net_global_local.py", line 201, in <module>
    rois_label, out_d_pixel, out_d = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/youedata/dengjinhong/github/DA_Detection/lib/model/faster_rcnn/faster_rcnn_global_local.py", line 114, in forward
    bbox_pred = self.RCNN_bbox_pred(pooled_feat)
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/nn/functional.py", line 992, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [256 x 2560], m2: [2304 x 84] at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCTensorMathBlas.cu:249
```

**Comment by kinredon** [comment]
I delete the argument `--bs 2`, the problem is fixed.

**Comment by mandyxiaomeng** [comment]
Hi, 
I am getting the same error. And I did not use --bs, I wonder if you have any suggestions? 
When I don't use --lc --gc, the code is working well. 

Thank you!

**Comment by kinredon** [comment]
Which file do you execute?

**Comment by mandyxiaomeng** [comment]
Hi, I use trainval_net_global_local.py. I realized only when I set the batch size to 1, the '--lc --gc' will not give the error of RuntimeError: size mismatch.

Do you have any suggestions?

**Comment by kinredon** [comment]
Just keep the bs = 1
